---
Name: myColor
---
SilverStripe\Admin\LeftAndMain:
  cms_background: '#1d48a0'
  cms_border_color: '#173778'
  cms_color: '#fff'
  cms_hover_background: 'inherit'
  cms_hover_color: currentColor
  cms_active_background: '#173778'
  cms_active_color: currentColor
  cms_drawer_background: '#1a3e88'
  cms_drawer_color: currentColor
  cms_icon_color: currentColor
  calendar_highlight_color: '#1d48a0'

---
Name: MemberClassExtension
---
SilverStripe\Security\Member:
  extensions:
    - MemberExtension

# ---
# Name: MemberExtension
# ---
# SilverStripe\Core\Injector\Injector:
#   SilverStripe\Security\Member:
#     class: MemberData


---
Name: ExtraJSCSSLeftAndMain
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - public/_resources/CSS/Admin.css
  extra_requirements_javascript:
    - public/_resources/JS/Admin.js

---
Name: CalendarFieldConfig
---
SilverStripe\Forms\FormField:
  calendar_datepicker_class: 'hasDatepicker'


---
Name: SiteConfigCustom
---
Silverstripe\SiteConfig\SiteConfig:
  extensions:
    - SiteConfigCustom

